apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deploy-test
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 5
  selector:
    matchLabels:
      tier: aws-test
  template:
    metadata:
      name: nginx-test
      labels:
        tier: aws-test
    spec:
      containers:
        - name: aws-test-container
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
           limits:
             cpu: "1"
             memory: "1Gi"
           requests:
             cpu: "0.2"
             memory: "512Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: project-hpa-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project-deploy-test
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
